# Generated by Django 4.2.3 on 2023-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Experience',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
    ]
